### ISSUE TITLE
glycan issue

### ISSUE THREAD

**Issue by kanghw0325** [chaidiscovery/chai-lab#218]
Hi, thank you for the great work.
I am currently using your covalent bond function (glycan function) and I got this kind of error.
this works
input.fasta file
```
>protein|name=6OIM
MKHHHHHHHDEVDGMTEYKLVVVGACGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETSLLDILDTAGQEEYSAMRDQYMRTGEGFLLVFAINNTKSFEDIHHYREQIKRVKDSEDVPMVLVGNKSDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQGVDDAFYTLVREIRKHKEK
>glycan|name=COV
MOV
>ligand|name=GDP
c1nc2c(n1[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)OP(=O)(O)O)O)O)N=C(NC2=O)N
```
bonds.restraints
```
chainA,res_idxA,chainB,res_idxB,connection_type,confidence,min_distance_angstrom,max_distance_angstrom,comment,restraint_id
A,C26@SG,B,@C25,covalent,1.0,0.0,0.0,protein-glycan,bond1
```
and this input does not work well but I got error with input down below.

input fasta
```
>protein|name=5NUD
MKHHHHHHHDEVDGMTEYKLVVVGACGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETSLLDILDTAGQEEYSAMRDQYMRTGEGFLLVFAINNTKSFEDIHHYREQIKRVKDSEDVPMVLVGNKSDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQGVDDAFYTLVREIRKHKEK
>glycan|name=COV
99K
>ligand|name=GDP
c1nc2c(n1[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)OP(=O)(O)O)O)O)N=C(NC2=O)N
```
bonds.restraints
```
chainA,res_idxA,chainB,res_idxB,connection_type,confidence,min_distance_angstrom,max_distance_angstrom,comment,restraint_id
A,C26@SG,B,@C7,covalent,1.0,0.0,0.0,protein-glycan,bond1
```
error
```
Traceback (most recent call last):
  File "/data/hwkang/chai1/covalent_test/run.py", line 16, in <module>
    candidates = run_inference(
                 ^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/chai_lab/chai1.py", line 373, in run_inference
    cov_a, cov_b = get_atom_covalent_bond_pairs_from_constraints(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 559, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 483, in wrapped_fn_impl
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/chai_lab/data/dataset/structure/bond_utils.py", line 46, in get_atom_covalent_bond_pairs_from_constraints
    right_asym_id = get_asym_id_from_subchain_id(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 559, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 483, in wrapped_fn_impl
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/hwkang/miniconda3/envs/chai_cov/lib/python3.12/site-packages/chai_lab/model/utils.py", line 212, in get_asym_id_from_subchain_id
    assert len(chain_id_asyms) == 1, (
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected only one token asym, but got 0 asyms: tensor([], dtype=torch.int32)
```
can I see how to fix this issue?

**Comment by wukevin** [comment]
I've merged a change to address this issue!

In general, if you get errors when specifying through CCD codes, SMILES string is going to be more robust and flexible.

**Comment by kanghw0325** [comment]
Thank you for fast response! Thank you so much!
