### ISSUE TITLE
Duplicate entity found

### ISSUE THREAD

**Issue by homemade-laboratory** [chaidiscovery/chai-lab#245]
Hey guys,
I'm trying to pass two ligands to the model, but I'm encountering the following error. Has anyone tried passing multiple ligands on a local installation? (Multiple proteins work fine for me.) I'm curious whether I'm doing something wrong with the input or if I should dig deeper into the code.

Traceback (most recent call last):
  File "/home/andrey/chai-lab/examples/predict_structure.py", line 51, in <module>
    candidates = run_inference(
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/andrey/chai-lab/chai_lab/chai1.py", line 474, in run_inference
    return run_folding_on_context(
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/andrey/chai-lab/chai_lab/chai1.py", line 910, in run_folding_on_context
    save_to_cif(
  File "/home/andrey/chai-lab/chai_lab/data/io/cif_utils.py", line 151, in save_to_cif
    new_context_to_cif_atoms(
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 559, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/jaxtyping/_decorator.py", line 483, in wrapped_fn_impl
    out = fn(*args, **kwargs)
  File "/home/andrey/chai-lab/chai_lab/data/io/cif_utils.py", line 242, in new_context_to_cif_atoms
    dumper.write(open(out_path, "w"), systems=[system])
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/modelcif/dumper.py", line 870, in write
    return ihm.dumper.write(fh, systems, format, dumpers, variant)
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/ihm/dumper.py", line 3989, in write
    d.finalize(system)
  File "/home/andrey/anaconda3/envs/chai/lib/python3.10/site-packages/ihm/dumper.py", line 370, in finalize
    raise ValueError("Duplicate entity %s found" % entity)
ValueError: Duplicate entity <ihm.Entity(ligand-2)> found

FASTA file I'm using:
```python
example_fasta = """
>protein|name=example-of-long-protein
MANFTPVNGSSGNQSVRLVTSSSHNRYETVEMVFIATVTGSLSLVTVVGNILVMLSIKVNRQLQTVNNYFLFSLACADLIIGAFSMNLYTVYIIKGYWPLGAVVCDLWLALDYVVSNASVMNLLIISFDRYFCVTKPLTYPARRTTKMAGLMIAAAWVLSFVLWAPAILFWQFVVGKRTVPDNQCFIQFLSNPAVTFGTAIAAFYLPVVIMTVLYIHISLASRSRVHKHRPEGPKEKKAVARKFASIARNQVRKKRQMAARERKVTRTIFAILLAFILTWTPYNVMVLVNTFCQSCIPDTVWSIGYWLCYVNSTINPACYALCNATFKKTFRHLLLCQYRNIGTAR
>ligand|name=ligand-1
CN1CCN(CC1)C(=O)COc1nc2sc(c(c2c(c1Cl)C)N)C(=O)NC1CC1
>ligand|name=ligand-2
C[N+](CC#CCOC1=NOCC1)(C)C
""".strip()

**Comment by mosayebi** [comment]
It seems a similar bug has recently been introduced for homopolymers.  See https://github.com/chaidiscovery/chai-lab/issues/67#issuecomment-2543386006 .
Rolling back (`git checkout f77f44165ef59bba0685f176d03ee4b02e793967`) resolves the issue.

**Comment by arogozhnikov** [comment]
@mosayebi thanks for reporting, please try PR https://github.com/chaidiscovery/chai-lab/pull/251 , problem should be fixed there
