### ISSUE TITLE
Another CUDA-related question: CutlassF error

### ISSUE THREAD

**Issue by alexberlaga** [chaidiscovery/chai-lab#46]
Hello! I have two GPUs: an NVIDIA L40S and an NVIDIA V100, both of which are running CUDA 12.2 (I have tried with CUDA 11.8/Pytorch 2.3.1, and the following error does not change). 

On the L40S, I can run the code with no problems. However, on the V100, I get the following error when using the size-256 model upon running folding:

```
Traceback (most recent call last):
  File "/project2/andrewferguson/berlaga/drugdiscovery/run_chai.py", line 60, in <module>
    output_pdb_paths = run_inference(
                       ^^^^^^^^^^^^^^
  File "/scratch/midway3/berlaga/miniconda3/envs/chai/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/midway3/berlaga/miniconda3/envs/chai/lib/python3.12/site-packages/chai_lab/chai1.py", line 293, in run_inference
    output_paths, scores, ranking_data = run_folding_on_context(
                                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/midway3/berlaga/miniconda3/envs/chai/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/midway3/berlaga/miniconda3/envs/chai/lib/python3.12/site-packages/chai_lab/chai1.py", line 421, in run_folding_on_context
    token_input_embedder_outputs: tuple[Tensor, ...] = token_input_embedder.forward(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<eval_with_key>.9", line 202, in forward
  File "/scratch/midway3/berlaga/miniconda3/envs/chai/lib/python3.12/site-packages/torch/_ops.py", line 594, in __call__
    return self_._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cutlassF: no kernel found to launch!
```
Is the code not supported on V100s? Otherwise, what could be causing this issue?

**Comment by arogozhnikov** [comment]
Hi Alex, this is same issue as #26 

I've updated readme to reflect supported GPUs. Both V100 and L40s don't support bfloat16.

**Comment by alexberlaga** [comment]
Thanks!
