### ISSUE TITLE
antipickle issue when running predict_structure.py example

### ISSUE THREAD

**Issue by dannyoo** [chaidiscovery/chai-lab#96]
Python 3.10.15

```
Traceback (most recent call last):
  File "/projects/mayhem/predict_structure.py", line 25, in <module>
    candidates = run_inference(
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/chai_lab/chai1.py", line 271, in run_inference
    chains = load_chains_from_raw(fasta_inputs)
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/chai_lab/data/dataset/inference_dataset.py", line 164, in load_chains_from_raw
    conformer_generator = RefConformerGenerator()
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/chai_lab/data/sources/rdkit.py", line 61, in __init__
    self.cached_conformers = self._load_apkl_conformers(conformers_cache_file)
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/chai_lab/data/sources/rdkit.py", line 71, in _load_apkl_conformers
    return antipickle.load(path, adapters=_get_adapters())
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/antipickle/__init__.py", line 129, in load
    loaded = list(load_sequence(f, adapters=adapters))
  File "/home/jimendi1/mambaforge/envs/chai1/lib/python3.10/site-packages/antipickle/__init__.py", line 75, in load_sequence
    raise AntipickleDeserializationError("Wrong format or corrupted file")
antipickle.AntipickleDeserializationError: Wrong format or corrupted file
```

**Comment by arogozhnikov** [comment]
"Wrong format or corrupted file" says it all - your downloaded conformers file is corrupted, delete and re-download

**Comment by dannyoo** [comment]
How can I specify the location of the locally downloaded file?

**Comment by arogozhnikov** [comment]
This fragment shows the path: 

```python
from chai_lab.utils import paths
print(paths.cached_conformers.get_path())
```

If you delete file, it should be automatically redownloaded
